site_name: yjs | study
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to light mode
  language: zh
  features:
    - navigation.tabs # 顶部分类标签
    - navigation.top # 返回顶部按钮
    - search.highlight # 搜索结果高亮

copyright: '三个字的学习博客'   

nav:
  - 首页: index.md
  - 构建mkdocs: mkdocs\index.md
  - agent:
      - 基础|单词: agent\00-单词-基础.md
      - 简介: agent\01-基本简介.md
      - 什么是智能体: agent\02-什么是智能体.md
      - 核心概念&流程: agent\03-核心概念&流程.md
      - 技术架构:
        - 技术架构-流程: agent\04-技术架构-组成&流程.md
        - 技术架构-profile(配置): agent\05-技术架构-profile(配置).md
        - 技术架构-Percept(感知): agent\06-技术架构-Percept(感知).md
        - 技术架构-Planning&Reasoning: agent\07-技术架构-Planning&Reasoning.md
        - 技术架构-Acttion(行动): agent\08-技术架构-Acttion(行动).md
        - 技术架构-Acttion(行动)-MCP: agent\08-技术架构-Acttion-MCP.md
  - agent-tv:
    - 基础概念: agent-tv\01-基础.md      
  - langchain:
      - 第一周基础入门:
        - day01: langchain\week01-基础入门\day01.md

